-- Persist payment-only Stripe identifiers on applications and add a general
-- admin audit ledger for business-critical application/document events.

ALTER TABLE public.applications
  ADD COLUMN IF NOT EXISTS stripe_checkout_session_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_payment_intent_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_invoice_id TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_applications_stripe_checkout_session_unique
  ON public.applications(stripe_checkout_session_id)
  WHERE stripe_checkout_session_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_applications_stripe_subscription_unique
  ON public.applications(stripe_subscription_id)
  WHERE stripe_subscription_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_applications_stripe_customer_id
  ON public.applications(stripe_customer_id)
  WHERE stripe_customer_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_applications_stripe_payment_intent_id
  ON public.applications(stripe_payment_intent_id)
  WHERE stripe_payment_intent_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_applications_stripe_invoice_id
  ON public.applications(stripe_invoice_id)
  WHERE stripe_invoice_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.admin_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  actor TEXT,
  application_id UUID REFERENCES public.applications(id) ON DELETE SET NULL,
  old_status TEXT,
  new_status TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_events_application_id
  ON public.admin_audit_events(application_id);

CREATE INDEX IF NOT EXISTS idx_admin_audit_events_action
  ON public.admin_audit_events(action);

CREATE INDEX IF NOT EXISTS idx_admin_audit_events_created_at
  ON public.admin_audit_events(created_at DESC);

ALTER TABLE public.admin_audit_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_full_access ON public.admin_audit_events;
CREATE POLICY admin_full_access
  ON public.admin_audit_events
  FOR ALL
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

NOTIFY pgrst, 'reload schema';
