CREATE TABLE IF NOT EXISTS public.stripe_webhook_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_event_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'received',
  error_message TEXT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMPTZ
);

ALTER TABLE public.stripe_webhook_events
  ALTER COLUMN stripe_event_id SET NOT NULL;

ALTER TABLE public.stripe_webhook_events
  ALTER COLUMN event_type SET NOT NULL;

ALTER TABLE public.stripe_webhook_events
  ALTER COLUMN status SET DEFAULT 'received';

ALTER TABLE public.stripe_webhook_events
  ALTER COLUMN received_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.stripe_webhook_events
  DROP CONSTRAINT IF EXISTS stripe_webhook_events_status_check;

ALTER TABLE public.stripe_webhook_events
  ADD CONSTRAINT stripe_webhook_events_status_check
  CHECK (status IN ('received', 'processing', 'processed', 'failed'));

CREATE UNIQUE INDEX IF NOT EXISTS idx_stripe_webhook_events_event_id
  ON public.stripe_webhook_events(stripe_event_id);

CREATE INDEX IF NOT EXISTS idx_stripe_webhook_events_processed_at
  ON public.stripe_webhook_events(processed_at DESC);

CREATE INDEX IF NOT EXISTS idx_stripe_webhook_events_status
  ON public.stripe_webhook_events(status);

ALTER TABLE public.stripe_webhook_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'stripe_webhook_events'
      AND policyname = 'admin_full_access'
  ) THEN
    CREATE POLICY admin_full_access ON public.stripe_webhook_events
      FOR ALL TO authenticated
      USING (is_admin());
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
