CREATE TABLE IF NOT EXISTS toll_transfer_notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rental_id BIGINT REFERENCES rentals(id) ON DELETE SET NULL,
  application_id UUID REFERENCES applications(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  car_id BIGINT REFERENCES cars(id) ON DELETE SET NULL,
  toll_notice_number TEXT NOT NULL,
  vehicle_registration TEXT NOT NULL,
  nominee_full_name TEXT NOT NULL,
  nominee_dob DATE,
  nominee_phone TEXT NOT NULL,
  nominee_address TEXT NOT NULL,
  nominee_suburb TEXT NOT NULL,
  nominee_state TEXT NOT NULL,
  nominee_postcode TEXT NOT NULL,
  nominee_country TEXT NOT NULL DEFAULT 'AUSTRALIA',
  responsible_type TEXT NOT NULL DEFAULT 'responsible',
  declaration_place TEXT NOT NULL,
  declaration_date DATE NOT NULL,
  authorised_officer_name TEXT NOT NULL,
  witness_name TEXT,
  witness_qualification TEXT,
  witness_jp_number TEXT,
  toll_trip_date DATE,
  pdf_url TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT toll_transfer_notices_status_check
    CHECK (status IN ('draft', 'generated', 'sent')),
  CONSTRAINT toll_transfer_notices_responsible_type_check
    CHECK (responsible_type IN ('responsible', 'new-owner', 'previous-owner'))
);

CREATE TABLE IF NOT EXISTS toll_transfer_notice_audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  toll_transfer_notice_id BIGINT REFERENCES toll_transfer_notices(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  actor TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_toll_transfer_notices_rental_id
  ON toll_transfer_notices(rental_id);
CREATE INDEX IF NOT EXISTS idx_toll_transfer_notices_application_id
  ON toll_transfer_notices(application_id);
CREATE INDEX IF NOT EXISTS idx_toll_transfer_notices_toll_notice_number
  ON toll_transfer_notices(toll_notice_number);
CREATE INDEX IF NOT EXISTS idx_toll_transfer_notice_audit_notice_id
  ON toll_transfer_notice_audit_events(toll_transfer_notice_id);

ALTER TABLE toll_transfer_notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE toll_transfer_notice_audit_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_full_access ON toll_transfer_notices;
DROP POLICY IF EXISTS admin_full_access ON toll_transfer_notice_audit_events;

CREATE POLICY admin_full_access ON toll_transfer_notices
  FOR ALL TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY admin_full_access ON toll_transfer_notice_audit_events
  FOR ALL TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());
