CREATE TABLE IF NOT EXISTS agreement_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_key TEXT NOT NULL DEFAULT 'car-lease',
  name TEXT NOT NULL DEFAULT 'Car Lease Agreement',
  content TEXT NOT NULL CHECK (char_length(content) BETWEEN 1 AND 50000),
  version INTEGER NOT NULL CHECK (version > 0),
  active BOOLEAN NOT NULL DEFAULT false,
  updated_by TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_agreement_templates_template_version
  ON agreement_templates(template_key, version);

CREATE UNIQUE INDEX IF NOT EXISTS idx_agreement_templates_active_template
  ON agreement_templates(template_key)
  WHERE active;

CREATE INDEX IF NOT EXISTS idx_agreement_templates_updated_at
  ON agreement_templates(updated_at DESC);

ALTER TABLE agreement_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_full_access ON agreement_templates;
CREATE POLICY admin_full_access ON agreement_templates
  FOR ALL TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

INSERT INTO agreement_templates (
  template_key,
  name,
  content,
  version,
  active,
  updated_by
)
SELECT
  'car-lease',
  'Car Lease Agreement',
  $template$# Car Lease Agreement

## 1. Registered Owner Details
- Name: {{registeredOwnerName}}
- Address: {{registeredOwnerAddress}}
- Contact: {{registeredOwnerContact}}
- Email: {{registeredOwnerEmail}}

## 2. Rentee Details
- Name: {{renteeName}}
- Date of Birth: {{renteeDob}}
- License Number: {{renteeLicenseNumber}}
- License State: {{renteeLicenseState}}
- Address: {{renteeAddress}}
- Contact: {{renteeContact}}
- Email: {{renteeEmail}}

## 3. Vehicle Details
- Make: {{vehicleMake}}
- Model: {{vehicleModel}}
- Year: {{vehicleYear}}
- VIN: {{vehicleVin}}
- KM Allowance: {{kmAllowance}}

## 4. Rental Fee / Cost
Your invoice is issued weekly and may include:
- Weekly rent
- Toll notice fee
- Account management fee
- Toll management fee
- Direct debit fee
- Other additional charges

Rentee agrees to pay:
- Weekly Rent: {{weeklyRent}}
- Fuel Policy: {{fuelPolicy}}

### Fee Schedule
{{feeSchedule}}

{{insuranceCoverage}}

## 5. Rental Period
- Starting Date: {{rentalStartDate}}
- Ending Date: {{rentalEndDate}}
- Minimum Rental Period: {{minimumRentalPeriod}}

## 6. Return Of Vehicle
{{returnPolicy}}

## 7. Legal Notice
The parties choose the addresses above as their physical addresses where legal proceedings may be instituted.

Date: {{agreementDate}}

Rentee Signature: _______________________________$template$,
  2,
  true,
  'migration'
WHERE NOT EXISTS (
  SELECT 1 FROM agreement_templates WHERE template_key = 'car-lease'
);
